version: "3"

services:
  app:
    build: .
    command: rails server -p 80 -b '0.0.0.0'
    volumes:
      - .:/app
      - gems:/gems
    ports:
      - "80:80"
    links:
      - postgres
  postgres:
    image: postgres:9.6.1
    ports:
      - "5432"

volumes:
  gems:
