// TEAM RELATED CONSTANTS
export const RECEIVE_TEAM = 'RECEIVE_TEAM'
export const INITIALIZE_PLAYERS = 'INITIALIZE_PLAYERS'
export const CHANGE_WEEK = 'CHANGE_WEEK'

// APP STATE RELATED
export const UPDATE_LOADING = 'UPDATE_LOADING'
