// TEAM RELATED CONSTANTS
export const RECEIVE_TEAM = 'RECEIVE_TEAM'
export const INITIALIZE_PLAYERS = 'INITIALIZE_PLAYERS'
export const CHANGE_WEEK = 'CHANGE_WEEK'
export const ADD_CURRENT_POSITIONS = 'ADD_POSITIONS'

// APP STATE RELATED
export const UPDATE_LOADING = 'UPDATE_LOADING'
